name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get install gcovr ninja-build
    - name: Setup
      run: |
        mkdir build
    - name: Configure
      working-directory: build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -GNinja ..
    - name: Build
      working-directory: build
      run: |
        cmake --build .
    - name: Run CTest
      working-directory: build/test
      run: |
        ctest --verbose
    - name: Run Test Coverage
      working-directory: build
      run: |
        cmake --build . --target coverage
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Test Coverage
        path: build/coverage
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup
      run: |
        mkdir build
    - name: Configure
      working-directory: build
      run: |
        cmake ..
      shell: cmd
    - name: Build
      working-directory: build
      run: |
        cmake --build .
      shell: cmd
    - name: Run CTest
      working-directory: build/test
      run: |
        ctest -C Debug --verbose
      shell: cmd

  build-macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup
      run: |
        mkdir build
    - name: Configure
      working-directory: build
      run: |
        cmake ..
    - name: Build
      working-directory: build
      run: |
        cmake --build .
    - name: Run CTest
      working-directory: build/test
      run: |
        ctest --verbose
