name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install gcovr ninja-build valgrind
    - name: Build
      run: |
        mkdir build
        cmake . -B build -GNinja -DSIMFIL_FPIC=YES -DSIMFIL_SHARED=NO
        cmake --build build
    - name: Run CTest
      working-directory: build/test
      run: |
        ctest --verbose --output-junit result-junit.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          build/test/*.xml

    - name: Run Valgrind Memcheck
      working-directory: build/test
      run: |
        valgrind --tool=memcheck ./test.simfil
    - name: Run Valgrind Helgrind
      working-directory: build/test
      run: |
        valgrind --tool=helgrind ./test.simfil
    - name: Run Valgrind Cachegrind
      working-directory: build/test
      run: |
        valgrind --tool=cachegrind ./test.simfil | tee cachegrind-out.txt
    - name: Run Valgrind Callgrind
      working-directory: build/test
      run: |
        valgrind --tool=callgrind --instr-atstart=no ./test.simfil
    - name: Publish Callgrind Output
      uses: actions/upload-artifact@v4
      with:
        name: Callgrind Output
        path: build/test/callgrind.out.*

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: |
        mkdir build
        cmake . -B build -DSIMFIL_FPIC=NO -DSIMFIL_SHARED=NO
        cmake --build build
    - name: Run CTest
      working-directory: build/test
      run: |
        ctest --verbose --output-junit result-junit.xml

  build-macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: |
        mkdir build
        cmake . -B build -DSIMFIL_FPIC=YES -DSIMFIL_SHARED=NO
        cmake --build build
    - name: Run CTest
      working-directory: build/test
      run: |
        ctest --verbose --output-junit result-junit.xml
