name: Conan
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Conan 2
      run: |
        pip install conan
        conan profile detect
    - name: Create
      run: |
        conan create . -s compiler.cppstd=20 --build=missing
